### ISSUE TITLE
Can I control what attribute is shown in the browser window?

### ISSUE THREAD

**Issue by magerlin** [3nids/itembrowser#5]
I would like to see another attribute than the one shown (with same value "Rahela Vlaovic" for all selected features):

![image](https://user-images.githubusercontent.com/1887531/30165409-47bbad38-93e0-11e7-94d3-dea93a0b11a0.png)

Is that possible?

**Comment by 3nids** [comment]
this is the display expression of the layer, you can change it in the properties

**Comment by magerlin** [comment]
Hmm - I cannot make that work. I have tried this:
![image](https://user-images.githubusercontent.com/1887531/30166089-8e70275c-93e2-11e7-895a-9d607bba9d6d.png)

And this:
![image](https://user-images.githubusercontent.com/1887531/30166066-7d66c024-93e2-11e7-89cc-03069ba668ca.png)

But it does not change that the attribute "Name" is shown in the browser window

**Comment by magerlin** [comment]
I am using Qgis 2.18.12 in Win 7 64 bit....

**Comment by 3nids** [comment]
Sorry, this is properly handled in coming QGIS 3.
To set the display expression of a layer in QGIS 2.x, you have to define it in the attribute table as a related layer -- not very easy way.
A solution would be to use a python command to do it:
`iface.activeLayer().setDisplayExpression( 'your_expression' )`
